spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: "customers"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
